import React from 'react';
import { Card, Hero, Layout, Page, Progress } from '../components/UI';
import { getEnglishDay } from '../data/english';
import { readStore, writeStore } from '../utils/storage';

export function English100() {
  const [day,setDay]=React.useState(()=>readStore('englishDay',1)); const [notes,setNotes]=React.useState(()=>readStore('englishNotes',{})); const [done,setDone]=React.useState(()=>readStore('englishDone',{})); const data=getEnglishDay(day); const complete=Object.values(done).filter(Boolean).length;
  const updateNotes=v=>{const n={...notes,[day]:v};setNotes(n);writeStore('englishNotes',n)}; const mark=()=>{const n={...done,[day]:!done[day]};setDone(n);writeStore('englishDone',n)};
  return <Layout><Page><Hero title="100 Days English Mentor" subtitle="Daily 30 sentences, Hindi meaning, 15 vocabulary, speaking tip, notes, completion tracking."><div className="scoreMini"><b>{complete}/100</b><Progress value={complete}/></div></Hero><Card title="Day Selector"><div className="row"><input type="range" min="1" max="100" value={day} onChange={e=>setDay(Number(e.target.value))}/><input type="number" min="1" max="100" value={day} onChange={e=>setDay(Math.max(1,Math.min(100,Number(e.target.value))))}/><button className="btn" onClick={mark}>{done[day]?'Mark Pending':'Mark Complete'}</button></div><p><b>Day {day}:</b> {data.topic} — {data.phase}</p><p className="hint">{data.goal}</p></Card><div className="grid2"><Card title="30 Daily-Use Sentences"><div className="scrollList">{data.sentences.map(s=><div className="sentence" key={s.no}><b>{s.no}. {s.english}</b><p>{s.hindi}</p></div>)}</div></Card><Card title="Vocabulary Builder"><div className="scrollList">{data.vocab.map(v=><div className="sentence" key={v.no}><b>{v.no}. {v.word}</b><p>{v.hindi} • {v.pronunciation}</p><small>{v.example}</small></div>)}</div><div className="tip"><b>Speaking Tip</b><p>{data.tip}</p></div></Card></div><Card title="My Speaking Notes"><textarea value={notes[day]||''} onChange={e=>updateNotes(e.target.value)} placeholder="Write mistakes, pronunciation notes, sentences used in real life..."/><button className="btn">Saved automatically</button></Card></Page></Layout>;
}
