import React from 'react';
import { Link } from 'react-router-dom';
import { Card, Field, Hero, Layout, Page, Stat, Progress } from '../components/UI';
import { companies, jobPortals } from '../data/companies';
import { profile, cvSkills } from '../data/profile';
import { keywordMatch } from '../utils/scoring';
import { downloadText, exportBackup, readStore, writeStore } from '../utils/storage';

export function JobTracker() {
  const [rows,setRows]=React.useState(()=>readStore('jobs',companies)); const [filter,setFilter]=React.useState({q:'',status:'All'}); const [selected,setSelected]=React.useState([]);
  const list=rows.filter(r=>(filter.status==='All'||r.status===filter.status)&&r.name.toLowerCase().includes(filter.q.toLowerCase())).slice(0,200); const update=(id,patch)=>{const n=rows.map(r=>r.id===id?{...r,...patch}:r);setRows(n);writeStore('jobs',n)};
  return <Layout><Page><Hero title="Job Tracker" subtitle="800 Salesforce company rows, website/search links, apply checklist, sorting, notes — same table-wise reference format."/><Card title="Filters & Bulk Actions"><div className="filterBar"><input value={filter.q} onChange={e=>setFilter({...filter,q:e.target.value})} placeholder="Search company"/><select value={filter.status} onChange={e=>setFilter({...filter,status:e.target.value})}>{['All','Saved','Applied','HR Call','Technical','Offer','Rejected'].map(x=><option key={x}>{x}</option>)}</select><button className="btn" onClick={()=>{const n=rows.map(r=>selected.includes(r.id)?{...r,status:'Applied',applied:true}:r);setRows(n);writeStore('jobs',n)}}>Bulk Applied</button><button className="btn ghost" onClick={()=>downloadText('job-tracker.json',JSON.stringify(rows,null,2),'application/json')}>Export</button></div></Card><div className="tableWrap"><table><thead><tr><th><input type="checkbox" onChange={e=>setSelected(e.target.checked?list.map(x=>x.id):[])}/></th><th>No.</th><th>Company</th><th>Status</th><th>Saved/Applied</th><th className="notesTh">Notes / Follow-up Details</th></tr></thead><tbody>{list.map(r=><tr key={r.id}><td><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(x=>x!==r.id))}/></td><td><span className="numBox">{r.id}</span></td><td><a href={r.website} target="_blank">🔗 <b>{r.name}</b><br/><small>{r.website}</small></a></td><td><select value={r.status} onChange={e=>update(r.id,{status:e.target.value,applied:e.target.value==='Applied'})}>{['Saved','Applied','HR Call','Technical','Offer','Rejected'].map(x=><option key={x}>{x}</option>)}</select></td><td><label className="checkPill"><input type="checkbox" checked={r.saved} onChange={e=>update(r.id,{saved:e.target.checked})}/> Saved</label><label className="checkPill"><input type="checkbox" checked={r.applied} onChange={e=>update(r.id,{applied:e.target.checked,status:e.target.checked?'Applied':r.status})}/> Applied</label></td><td className="jobNotesCell"><textarea className="jobNoteArea" value={r.notes} onChange={e=>update(r.id,{notes:e.target.value})} placeholder="Applied link / recruiter / follow-up / interview notes..."/><div className="row"><button className="btn small cyan" onClick={()=>update(r.id,{notes:r.notes, noteSavedAt:new Date().toLocaleString()})}>💾 Save Note</button><small>{r.noteSavedAt}</small></div></td></tr>)}</tbody></table></div><p className="hint">All changes save in localStorage. Use Backup Center regularly.</p></Page></Layout>;
}

export function MoreTools() {
  const jobs=readStore('jobs',companies); const notes=readStore('notes',[]); const docs=readStore('documents',[]); const applied=jobs.filter(j=>j.applied||j.status==='Applied').length;
  const tools=[['Learning Coach','Smart daily plan, sprint timer, mistake bank, quiz, recap, and LinkedIn proof generator.','/learning-coach'],['24 Hours Time Tracker','Track every hour/minute: study, project, interview, job apply, break, and daily productivity dashboard.','/time-tracker'],['Notes Library','View/edit/delete/open uploaded notes and files.','/notes'],['Document Library','Central place for topic PDFs, Word files, images, and code files.','/documents'],['Job Tracker','800 Salesforce company rows, website/search links, apply checklist, sorting, notes.','/job-tracker'],['Weekly Question Papers','Topic-wise 30-question paper for every week.','/weekly-tests'],['Skill Gap Analysis','Track Admin, Flow, Apex, Trigger, LWC, Integration skill strength.','/practice'],['Weak Topic Tracker','Mark weak topics, plan revision, and track improvement.','/focus'],['Revision Calendar','Spaced revision schedule: 1/3/7/15/30 day revision.','/weekly-tests'],['Doubt Tracker','Store doubts with status, priority, answer, and next action.','/doubts'],['Learning Journal','Daily reflection: learned, practiced, mistake, tomorrow.','/journal'],['Certification Tracker','Admin, App Builder, PD1, AI Associate, Agentforce Specialist.','/certifications'],['Trailhead Tracker','Your Trailhead profile link, badges, modules, status.','/certifications'],['JD Matcher','Paste JD and compare Salesforce keywords locally.','/jd-matcher'],['Resume Optimizer','Edit resume fields and check ATS readiness.','/resume'],['Backup Center','Export local app data as JSON.','/backup'],['Storage Health','Show localStorage/file usage summary.','/backup']];
  const resources=[['My Trailhead Profile',profile.trailhead],['Salesforce Trailhead','https://trailhead.salesforce.com'],['Apex Developer Guide','https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/'],['LWC Developer Guide','https://developer.salesforce.com/docs/platform/lwc/overview'],['SOQL/SOSL Guide','https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/'],['Flow Builder','https://help.salesforce.com/s/articleView?id=sf.flow.htm&type=5'],['Salesforce Careers','https://careers.salesforce.com']];
  return <Layout><Page><Hero title="More Tools" subtitle="All job-ready tools are connected with useful data, links, and working local actions."/><div className="statsGrid"><Stat label="Notes" value={notes.length} icon="📝"/><Stat label="Files" value={docs.length} icon="🗂️"/><Stat label="Companies" value="800" icon="🏢"/><Stat label="Applied" value={applied} icon="✅"/></div><div className="toolList">{tools.map(([t,d,l])=><Card key={t} title={t} subtitle={d} action={<Link className="btn" to={l}>Open Tool</Link>}/>)}</div><Card title="Quick Resources"><div className="resourceGrid">{resources.map(([t,l])=><a className="btn ghost" key={t} href={l} target="_blank">{t}</a>)}</div></Card></Page></Layout>;
}

export function JDMatcher() {
  const [jd,setJd]=React.useState(()=>readStore('jdText','Paste Salesforce JD here...')); const [resume,setResume]=React.useState(()=>readStore('resumeText',`${profile.summary}\n${Object.values(cvSkills).flat().join(', ')}`)); const result=keywordMatch(jd,resume);
  const save=()=>{writeStore('jdText',jd);writeStore('resumeText',resume)};
  return <Layout><Page><Hero title="JD Matcher" subtitle="Editable JD + resume keywords, score, missing keywords, portals, local applied tracking."/><div className="grid2"><Card title="Job Description"><textarea value={jd} onChange={e=>setJd(e.target.value)}/></Card><Card title="Your Resume/Profile Keywords"><textarea value={resume} onChange={e=>setResume(e.target.value)}/></Card></div><Card title="Match Result"><h1>{result.score}% Match</h1><Progress value={result.score}/><p><b>Matched:</b> {result.matched.slice(0,30).join(', ')}</p><p><b>Missing:</b> {result.missing.slice(0,30).join(', ')}</p><div className="row"><button className="btn" onClick={save}>Save JD</button>{jobPortals.map(([n,l])=><a className="btn ghost" target="_blank" href={l} key={n}>{n}</a>)}</div></Card></Page></Layout>;
}
