import React from 'react';
import { Link } from 'react-router-dom';
import { Card, Hero, Layout, Page, Progress } from '../components/UI';
import { roadmap90 } from '../data/roadmap';
import { questionBank } from '../data/questions';
import { readStore, writeStore } from '../utils/storage';

export function MentorRoute() {
  const [day,setDay]=React.useState(()=>readStore('mentorDay',1)); const d=roadmap90[day-1]||roadmap90[0]; const [done,setDone]=React.useState(()=>readStore('mentorDone',{}));
  const toggle=k=>{const n={...done,[`${day}-${k}`]:!done[`${day}-${k}`]};setDone(n);writeStore('mentorDone',n);writeStore('mentorDay',day)};
  const tasks=[['Salesforce',d.salesforce],['DSA',d.dsa],['System Design',d.systemDesign],['English',`Day ${d.englishDay}`],['Project',d.projectTask],['Interview',d.interviewTask]];
  const percent=tasks.filter(([k])=>done[`${day}-${k}`]).length/tasks.length*100;
  return <Layout><Page><Hero title="90-Day Zero to Hero Mentor Route" subtitle="Daily Salesforce + DSA + English + System Design + Project + Interview task."><div className="scoreMini"><b>Day {day}</b><Progress value={percent}/></div></Hero><Card title="Choose Day"><div className="row"><input type="range" min="1" max="90" value={day} onChange={e=>setDay(Number(e.target.value))}/><input type="number" min="1" max="90" value={day} onChange={e=>setDay(Number(e.target.value))}/></div></Card><div className="taskGrid">{tasks.map(([k,v])=><button key={k} className={done[`${day}-${k}`]?'taskDone taskCard':'taskCard'} onClick={()=>toggle(k)}><b>{k}</b><span>{v}</span><small>{done[`${day}-${k}`]?'Completed':'Click to complete'}</small></button>)}</div></Page></Layout>;
}

export function FocusMode() {
  const [day,setDay]=React.useState(()=>readStore('focusDay',1)); const [answers,setAnswers]=React.useState(()=>readStore('focusAnswers',{})); const [weakStrong,setWeakStrong]=React.useState(()=>readStore('weakStrong',{}));
  const route=roadmap90[(day-1)%roadmap90.length]; const qs=questionBank.filter(q=>[route.salesforce,route.dsa,route.systemDesign].includes(q.topic)).slice(0,20);
  const save=(id,text)=>{const n={...answers,[id]:{text,savedAt:new Date().toLocaleString(),status:'Saved'}};setAnswers(n);writeStore('focusAnswers',n)};
  const mark=(id,status)=>{const n={...weakStrong,[id]:status};setWeakStrong(n);writeStore('weakStrong',n)};
  const del=(id)=>{const n={...answers}; delete n[id]; setAnswers(n); writeStore('focusAnswers',n); const w={...weakStrong}; delete w[id]; setWeakStrong(w); writeStore('weakStrong',w)};
  return <Layout><Page><Hero title="Focus Mode" subtitle=""><div className="row"><input type="number" min="1" max="90" value={day} onChange={e=>setDay(Number(e.target.value))}/><span className="pill">{route.phase}</span></div></Hero><Card title="Today's Motivation"><p className="motivation">Great dreams of great dreamers are always transcended. Aaj ek answer save karo, ek topic strong mark karo, aur ek doubt clear karo.</p></Card><div className="listGap">{qs.length ? qs.map((q,i)=><Card key={q.id} title={`${i+1}. ${q.title}`} subtitle={`${q.track} • ${q.topic}`} action={<a className="btn small ghost" href={q.link} target="_blank">Open Link</a>}><p>{q.question}</p><textarea className="answerBox" value={answers[q.id]?.text||''} onChange={e=>save(q.id,e.target.value)} placeholder="Write answer here"/><div className="answerMeta"><span className="pill">{answers[q.id]?.status || 'Not saved'}</span><span className="pill">{weakStrong[q.id]||'Not marked'}</span><small>{answers[q.id]?.savedAt}</small></div><div className="row"><button className="btn cyan" onClick={()=>save(q.id,answers[q.id]?.text||'My focus answer saved.')}>Save</button><button className="btn ghost" onClick={()=>mark(q.id,'Weak')}>Weak</button><button className="btn ghost" onClick={()=>mark(q.id,'Strong')}>Strong</button><button className="btn danger" onClick={()=>del(q.id)}>Delete</button></div></Card>) : <Card title="No exact questions found"><p>Open Practice Lab for more topic-wise questions.</p><Link className="btn" to="/practice">Practice Lab</Link></Card>}</div></Page></Layout>;
}

export function LearningCoach() {
  const answers=readStore('answers',{}); const weak=readStore('weakStrong',{}); const weakCount=Object.values(weak).filter(x=>x==='Weak').length; const strongCount=Object.values(weak).filter(x=>x==='Strong').length;
  return <Layout><Page><Hero title="Learning Coach" subtitle="Smart daily plan, sprint timer, mistake bank, quiz, recap, and LinkedIn proof generator."/><div className="grid2"><Card title="Smart Plan"><ol><li>Complete one 45-minute Salesforce sprint</li><li>Solve 2 DSA questions</li><li>Revise weak topics: {weakCount}</li><li>Convert one answer into interview proof</li></ol><Link className="btn cyan" to="/focus">Start Focus</Link></Card><Card title="Mistake Bank"><p>Saved answers: {Object.keys(answers).length}</p><p>Weak topics: {weakCount}</p><p>Strong topics: {strongCount}</p><p>Rule: revise weak topic after 1/3/7/15/30 days.</p></Card><Card title="Quiz Generator"><p>Use Practice Lab filters and answer 10 questions from one topic.</p><Link className="btn" to="/practice">Open Practice Lab</Link></Card><Card title="LinkedIn Proof Generator"><textarea placeholder="Today I learned... I practiced... My project proof is..."/><button className="btn">Save Draft</button></Card></div></Page></Layout>;
}

export function AIMentor() {
  const [q,setQ]=React.useState(''); const [log,setLog]=React.useState(()=>readStore('mentorLog',[])); const [mode,setMode]=React.useState('local');
  function saveToNotes(item){ const notes=readStore('notes',[]); const n=[...notes,{id:Date.now(),title:item.q,body:item.answer,status:'Mentor',createdAt:new Date().toLocaleString()}]; writeStore('notes',n); alert('Saved to Notes Library'); }
  function deleteMentorItem(time){ const next=log.filter(item=>item.time!==time); setLog(next); writeStore('mentorLog',next); }
  async function ask(){ if(!q.trim()) return; let answer=''; if(mode==='backend'){ try{ const r=await fetch('http://127.0.0.1:8000/api/mentor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})}); const data=await r.json(); answer=data.answer; }catch{ answer='Backend/Ollama offline. Search links are ready below.'; } } if(!answer){ const saved=Object.values(readStore('answers',{})).find(a=>(a?.text||'').toLowerCase().includes(q.toLowerCase())); answer=saved ? `Found in your saved app data: ${saved.text}` : `Local mentor: For "${q}", no exact saved answer found. Use the links below, then save a final note. Structure: concept → real scenario → implementation → interview answer → revision action.`; } const links=[`https://www.google.com/search?q=${encodeURIComponent(q)}`,`https://help.salesforce.com/s/search-result?q=${encodeURIComponent(q)}`,`https://developer.salesforce.com/docs?q=${encodeURIComponent(q)}`,`https://trailhead.salesforce.com/search?keywords=${encodeURIComponent(q)}`]; const next=[...log,{q,answer,links,mode,time:new Date().toLocaleString()}]; setLog(next); writeStore('mentorLog',next); setQ(''); }
  return <Layout><Page><Hero title="AI Mentor Agent" subtitle=""><div className="row"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="local">Local App Data</option><option value="backend">Backend/Ollama</option></select></div></Hero><Card title="Ask Mentor"><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask Salesforce, DSA, JD, project, interview, error..."/><div className="row"><button className="btn cyan" onClick={ask}>Ask & Save</button><button className="btn ghost" onClick={()=>window.open(`https://www.google.com/search?q=${encodeURIComponent(q)}`,'_blank')}>Search Web</button></div></Card><div className="listGap">{log.slice().reverse().map((m,i)=><Card key={i} title={m.q} subtitle={`${m.mode} • ${m.time}`}><p>{m.answer}</p><div className="row">{m.links?.map(l=><a className="btn ghost" key={l} target="_blank" href={l}>Open Link</a>)}<button className="btn cyan" onClick={()=>saveToNotes(m)}>Save to Notes</button><button className="btn danger" onClick={()=>deleteMentorItem(m.time)}>Delete</button></div></Card>)}</div></Page></Layout>;
}
