import React from 'react';
import { Card, Hero, Layout, Page, Progress } from '../components/UI';
import { readStore, writeStore, exportBackup, downloadText } from '../utils/storage';

const categories = ['Reading / Theory','Salesforce Study','Hands-on Project','Interview Practice','Notes / Revision','Resume / LinkedIn','Job Apply','Portfolio Building','Trailhead / Certification','Coding Practice','Project Documentation','Sleep','Eating','Washroom / Freshen Up','Travelling','Calling / Communication','Movie / Entertainment','Television','Social Media','Exercise / Walk','Personal Work','Break','Other'];
const productiveCats = ['Reading / Theory','Salesforce Study','Hands-on Project','Interview Practice','Notes / Revision','Resume / LinkedIn','Job Apply','Portfolio Building','Trailhead / Certification','Coding Practice','Project Documentation'];
const defaultBlocks = [
  ['09:00','10:00','Salesforce Study','Daily topic study',''], ['10:15','11:00','Hands-on Project','Practice implementation',''], ['18:30','19:15','Coding Practice','DSA practice',''], ['20:00','20:45','Interview Practice','Mock interview','']
].map((x,i)=>({id:i+1,start:x[0],end:x[1],category:x[2],task:x[3],notes:x[4],done:false,productive:productiveCats.includes(x[2])}));
function minutesBetween(start,end){ const [sh,sm]=String(start||'00:00').split(':').map(Number); const [eh,em]=String(end||'00:00').split(':').map(Number); let m=(eh*60+em)-(sh*60+sm); return m>0?m:0; }
function fmt(min){ const h=Math.floor(min/60); const m=min%60; return `${h}h ${m}m`; }

export function TimeTracker() {
  const [day,setDay]=React.useState(()=>readStore('timeCurrentDay',1));
  const [all,setAll]=React.useState(()=>readStore('timeTasksByDay',{}));
  const tasks=all[day] || defaultBlocks;
  const [form,setForm]=React.useState({start:'09:00',end:'10:00',category:'Salesforce Study',task:'',notes:''});
  const saveDay=(items)=>{ const n={...all,[day]:items}; setAll(n); writeStore('timeTasksByDay',n); writeStore('timeCurrentDay',day); writeStore('timeTasks',items); };
  const update=(id,patch)=>saveDay(tasks.map(t=>t.id===id?{...t,...patch}:t));
  const add=()=>{ if(!form.task.trim()) return; saveDay([...tasks,{...form,id:Date.now(),done:false,productive:productiveCats.includes(form.category)}]); setForm({...form,task:'',notes:''}); };
  const duplicate=(t)=>saveDay([...tasks,{...t,id:Date.now(),task:t.task+' copy',done:false}]);
  const quick=(category,min,task)=>{ const now=new Date(); const start=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`; const endDate=new Date(now.getTime()+min*60000); const end=`${String(endDate.getHours()).padStart(2,'0')}:${String(endDate.getMinutes()).padStart(2,'0')}`; saveDay([...tasks,{id:Date.now(),start,end,category,task,notes:'Quick sprint',done:true,productive:productiveCats.includes(category)}]); };
  const total=tasks.reduce((a,t)=>a+minutesBetween(t.start,t.end),0); const doneMin=tasks.filter(t=>t.done).reduce((a,t)=>a+minutesBetween(t.start,t.end),0); const productive=tasks.filter(t=>productiveCats.includes(t.category)).reduce((a,t)=>a+minutesBetween(t.start,t.end),0); const jobMin=tasks.filter(t=>t.category==='Job Apply').reduce((a,t)=>a+minutesBetween(t.start,t.end),0); const focusScore=total?Math.round(productive/total*100):0;
  const stats=categories.map(c=>({cat:c,min:tasks.filter(t=>t.category===c).reduce((a,t)=>a+minutesBetween(t.start,t.end),0)})).filter(x=>x.min>0);
  const exportReport=()=>downloadText(`day-${day}-time-report.txt`, `Day ${day} 24h Tracker\nTracked: ${fmt(total)}\nProductive: ${fmt(productive)}\nDone: ${fmt(doneMin)}\nFocus Score: ${focusScore}%\n\n`+tasks.map(t=>`${t.start}-${t.end} | ${t.category} | ${t.task} | ${t.done?'Done':'Pending'} | ${t.notes}`).join('\n'));
  return <Layout><Page><Hero title="24 Hours Time Tracker" subtitle="Day 1-90 records, graph, quick sprint, editable blocks, daily report, focus score."><div className="scoreMini"><b>Day {day}</b><Progress value={focusScore}/></div></Hero>
    <Card title="Choose Day + Quick Sprints" subtitle="Har day ka record alag save hota hai"><div className="row"><input style={{maxWidth:140}} type="number" min="1" max="90" value={day} onChange={e=>setDay(Math.max(1,Math.min(90,Number(e.target.value)||1)))}/><button className="btn ghost" onClick={()=>saveDay(defaultBlocks)}>Load Template</button><button className="btn ghost" onClick={exportReport}>Export Daily Report</button><button className="btn cyan" onClick={()=>quick('Salesforce Study',45,'45-min Salesforce sprint')}>+45m Salesforce</button><button className="btn cyan" onClick={()=>quick('Coding Practice',30,'30-min DSA sprint')}>+30m DSA</button><button className="btn cyan" onClick={()=>quick('Job Apply',30,'30-min job apply')}>+30m Job Apply</button></div></Card>
    <div className="statsGrid"><div className="stat"><span>⏱️</span><p>Tracked Today</p><b>{fmt(total)}</b><small>Day {day}</small></div><div className="stat"><span>📚</span><p>Study Blocks</p><b>{tasks.filter(t=>productiveCats.includes(t.category)).length}</b><small>{fmt(productive)} productive</small></div><div className="stat"><span>💼</span><p>Job Actions</p><b>{fmt(jobMin)}</b><small>Apply/follow-up</small></div><div className="stat"><span>🎯</span><p>Focus Score</p><b>{focusScore}%</b><small>Productive / total</small></div></div>
    <Card title="Add Time Block" subtitle="Start/end time se duration auto calculate hoga"><div className="timeForm"><input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/><input type="time" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select><input value={form.task} onChange={e=>setForm({...form,task:e.target.value})} placeholder="What are you doing?"/><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Notes / result / proof"/><button className="btn cyan" onClick={add}>Save Block</button></div></Card>
    <div className="grid2"><Card title="Category Graph" subtitle="Work ke accordingly time distribution"><div className="barGraph">{stats.map(s=><div className="barRow" key={s.cat}><b>{s.cat}</b><div><i style={{width:`${Math.max(4,total?s.min/total*100:0)}%`}}/></div><span>{fmt(s.min)}</span></div>)}</div></Card><Card title="24 Hour Heatmap" subtitle="Filled blocks show active work slots"><div className="heatmap">{Array.from({length:24},(_,h)=>{ const active=tasks.some(t=>{const st=Number(String(t.start).split(':')[0]); const en=Number(String(t.end).split(':')[0]); return h>=st && h<=en;}); return <span key={h} className={active?'on':''} title={`${h}:00`}>{h}</span>})}</div><div className="tip"><b>Learning Guidance</b><p>{productive<180?'Learning time is low today. Complete one 45-minute Salesforce sprint before entertainment.':'Good productive base today. Add one interview answer and one job follow-up.'}</p><p>Balance: Learning {fmt(productive)} • Career {fmt(jobMin)} • Other {fmt(Math.max(0,total-productive-jobMin))}</p></div></Card></div>
    <Card title="Saved Day Blocks" subtitle="Edit, delete, duplicate, done/undo"><div className="timeCards">{tasks.map(t=><div className={t.done?'timeCard done':'timeCard'} key={t.id}><div><b>{t.start} - {t.end}</b><span>{fmt(minutesBetween(t.start,t.end))}</span></div><select value={t.category} onChange={e=>update(t.id,{category:e.target.value,productive:productiveCats.includes(e.target.value)})}>{categories.map(c=><option key={c}>{c}</option>)}</select><input value={t.task} onChange={e=>update(t.id,{task:e.target.value})}/><textarea value={t.notes||''} onChange={e=>update(t.id,{notes:e.target.value})} placeholder="Proof / result / notes"/><div className="row"><button className="btn small" onClick={()=>update(t.id,{done:!t.done})}>{t.done?'Undo':'Done'}</button><button className="btn small ghost" onClick={()=>duplicate(t)}>Duplicate</button><button className="btn small danger" onClick={()=>saveDay(tasks.filter(x=>x.id!==t.id))}>Delete</button></div></div>)}</div></Card>
  </Page></Layout>;
}

function SimpleCrud({ storeKey, title, placeholder, fields = ['title','body','status'] }) {
  const [items,setItems]=React.useState(()=>readStore(storeKey,[])); const [form,setForm]=React.useState({title:'',body:'',status:'Open',priority:'Medium',answer:'',nextAction:''});
  const save=()=>{if(!form.title.trim())return; const n=[...items,{...form,id:Date.now(),createdAt:new Date().toLocaleString()}];setItems(n);writeStore(storeKey,n);setForm({title:'',body:'',status:'Open',priority:'Medium',answer:'',nextAction:''})};
  const update=(id,patch)=>{const n=items.map(x=>x.id===id?{...x,...patch}:x);setItems(n);writeStore(storeKey,n)};
  const remove=(id)=>{const n=items.filter(x=>x.id!==id);setItems(n);writeStore(storeKey,n)};
  return <Layout><Page><Hero title={title} subtitle={placeholder}/><Card title="Add New"><div className="grid2"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Title"/><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Open</option><option>In Progress</option><option>Done</option></select></div><textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder={placeholder}/>{fields.includes('priority')&&<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select>}{fields.includes('answer')&&<textarea value={form.answer} onChange={e=>setForm({...form,answer:e.target.value})} placeholder="Answer / explanation"/>}<button className="btn cyan" onClick={save}>Save</button></Card><div className="listGap">{items.map(i=><Card key={i.id} title={i.title} subtitle={i.createdAt} action={<button className="btn danger small" onClick={()=>remove(i.id)}>Delete</button>}><div className="grid2"><input value={i.title} onChange={e=>update(i.id,{title:e.target.value})}/><select value={i.status} onChange={e=>update(i.id,{status:e.target.value})}><option>Open</option><option>In Progress</option><option>Done</option></select></div><textarea value={i.body} onChange={e=>update(i.id,{body:e.target.value})}/>{fields.includes('priority')&&<select value={i.priority||'Medium'} onChange={e=>update(i.id,{priority:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select>}{fields.includes('answer')&&<textarea value={i.answer||''} onChange={e=>update(i.id,{answer:e.target.value})} placeholder="Answer"/>}<button className="btn ghost" onClick={()=>update(i.id,{updatedAt:new Date().toLocaleString()})}>Save Edit</button></Card>)}</div></Page></Layout>;
}

export const Notes = () => <SimpleCrud storeKey="notes" title="Notes Library" placeholder="Save/edit/delete notes and proof."/>;
export const Doubts = () => <SimpleCrud storeKey="doubts" title="Doubt Tracker" placeholder="Store doubts with status, priority, answer, and next action." fields={['title','body','status','priority','answer']}/>;
export const Journal = () => <SimpleCrud storeKey="journal" title="Learning Journal" placeholder="Daily reflection: learned, practiced, mistake, tomorrow."/>;

export function Documents() {
  const [docs,setDocs]=React.useState(()=>readStore('documents',[])); async function add(e){const f=e.target.files[0]; if(!f)return; const data=await new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(f)}); const n=[...docs,{id:Date.now(),name:f.name,size:f.size,type:f.type,data,desc:''}];setDocs(n);writeStore('documents',n)}
  return <Layout><Page><Hero title="Document Library" subtitle="Central place for topic PDFs, Word files, images, and code files."/><Card title="Upload"><input type="file" onChange={add}/></Card><div className="grid3">{docs.map(d=><Card key={d.id} title={d.name} subtitle={`${Math.round(d.size/1024)} KB`}><textarea value={d.desc} onChange={e=>{const n=docs.map(x=>x.id===d.id?{...x,desc:e.target.value}:x);setDocs(n);writeStore('documents',n)}} placeholder="Details"/><div className="row"><a className="btn" target="_blank" href={d.data}>Open</a><button className="btn danger" onClick={()=>{const n=docs.filter(x=>x.id!==d.id);setDocs(n);writeStore('documents',n)}}>Delete</button></div></Card>)}</div></Page></Layout>;
}

export function Backup() {
  return <Layout><Page><Hero title="Backup Center & Storage Health" subtitle="Export local app data as JSON and check localStorage usage."/><Card title="Backup"><button className="btn cyan" onClick={exportBackup}>Export Backup JSON</button><p className="hint">Import can be added by reading the JSON and restoring localStorage keys.</p></Card><Card title="Storage Health"><p>Total localStorage keys: {localStorage.length}</p><p>Approx usage: {Math.round(JSON.stringify(localStorage).length/1024)} KB</p></Card></Page></Layout>;
}
